spring:
  application:
    name: dubbo-doc-example-provider
  profiles:
    active: dev
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  provider:
    timeout: 2000
  protocol:
    port: 20881
    name: dubbo
  application:
    name: dubbo-doc-example-provider